swagger: "2.0"
info:
  description: "Possible endpoints API for phase two of Argent Bank project."
  version: "1.0.0"
  title: "Argent Bank API Documentation"
  termsOfService: "http://swagger.io/terms/"

host: "localhost:3001"
basePath: "/api/v2"
tags:
  - name: "User Profile"
    description: "Endpoints for user profile"

  - name: "User Transactions View"
    description: "Endpoints for all transactions viewer"

  - name: "User Transaction Id detail"
    description: "Endpoints for user's transactions"

schemes:
  - "https"
  - "http"
paths:
  /user/profile:
    post:
      security:
        - Bearer: [ ]
      tags:
        - User Profile
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: [ ]
      tags:
        - User Profile
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/transactionsView/${transactionId}:
    post:
      security:
        - Bearer: [ ]
      tags:
        - User Transactions View
      summary: User Transactions
      description: API for fetching a transaction detail
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          description: "Attach Bearer JWT Token"
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      tags:
        - User Transactions View
      summary: "Update transaction details"
      description: ""
      operationId: "updateSavings"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          description: "Attach Bearer JWT Token"
          required: true
        - in: path
          name: accountTypeID
          type: integer
          required: true
          description: "Numeric ID of the type of transaction to get"
        - in: "body"
          name: "body"
          description: "Details that need to be updated"
          required: true
          schema:
            type: "object"
            properties:
              category:
                type: "string"
              notes:
                type: "string"
        - in: path
          name: transactionID
          type: integer
          required: true
          description: "Numeric ID of the transaction to get"
      responses:
        "200":
          description: Transaction details updated succesfully"
          schema:
            items:
              type: "object"
              properties:
                status:
                  type: "integer"
                  format: "int32"
                message:
                  type: "string"
                body:
                  type: "object"
                  properties:
                    category:
                      type: "string"
                    notes:
                      type: "string"

        "400":
          description: "Invalid fields"
        "500":
          description: "Internal server error"
  /user/profile/transactionsView/${transactionId}/detail:
    get:
      security:
        - Bearer: [ ]
      tags:
        - User Transaction Id detail
      summary: User Transactions
      description: API for fetching a transaction detail
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          description: "Attach Bearer JWT Token"
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: [ ]
      tags:
        - User Transaction Id detail
      summary: User Transactions
      description: ""
      operationId: "updateSavings"
        consumes:
          - "application/json"
          produces:
            - "application/json"
          responses:
            "200":
              description: Transaction details updated succesfully"
              schema:
                items:
                  type: "object"
                  properties:
                    status:
                      type: "integer"
                      format: "int32"
                    message:
                      type: "string"
                    body:
                      type: "object"
                      properties:
                        category:
                          type: "string"
                        notes:
                          type: "string"
definitions:
  User Profile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  User Transactions View:
    type: object
    properties:
      id:
        type: "integer"
        format: "int32"
      transaction:
        type: "object"
        properties:
          date:
            type: "string"
          description:
            type: "string"
          amount:
            type: "integer"
          type:
            type: "string"
          category:
            type: "string"
          notes:
            type: "string"
          User Transaction Id detail:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string